In [3]:
import tslearn
import numpy as np
from tslearn.datasets import UCR_UEA_datasets
X_train, y_train, X_test, y_test = UCR_UEA_datasets().load_dataset("Heartbeat")

In [4]:
print(X_train)
print(y_train)

[[[9.4900e-04 1.2880e-03 5.2900e-04 ... 7.8312e-02 4.5608e-02 1.2107e-01]
  [1.4880e-03 1.1400e-03 1.6350e-03 ... 1.4568e-01 1.1980e-01 1.3385e-01]
  [3.1400e-04 4.3000e-04 2.1460e-03 ... 2.3805e-01 1.7813e-01 4.0077e-02]
  ...
  [8.0400e-04 1.3640e-03 1.1790e-03 ... 4.4070e-01 3.7934e-01 9.8976e-02]
  [8.1500e-04 3.6300e-04 3.6300e-04 ... 6.3277e-01 3.7387e-01 2.5955e-02]
  [1.3890e-03 8.4300e-04 5.0400e-04 ... 6.5026e-01 3.2700e-01 3.6082e-02]]

 [[2.0264e-02 2.7680e-02 2.3423e-02 ... 7.8027e-01 5.4370e-01 2.4570e-03]
  [1.7023e-02 3.6928e-02 4.1957e-02 ... 4.4498e-01 1.6080e-01 5.0050e-01]
  [6.0520e-03 3.4255e-02 3.4538e-02 ... 4.9525e-01 5.4133e-01 7.2808e-01]
  ...
  [5.3840e-03 1.5869e-02 9.0860e-03 ... 9.8392e-02 1.0935e-01 1.8733e-01]
  [8.3720e-03 8.6480e-03 9.5190e-03 ... 2.0994e-01 2.5578e-01 5.0635e-02]
  [7.8450e-03 2.5470e-03 7.3490e-03 ... 4.6098e-01 4.1651e-01 1.7935e-01]]

 [[2.1082e-02 1.9906e-02 1.9319e-02 ... 1.9674e-01 3.4641e-01 1.4322e-01]
  [2.0687e-02 1.9558e-

In [6]:
from tslearn.neighbors import KNeighborsTimeSeriesClassifier
knn = KNeighborsTimeSeriesClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
print(knn.score(X_test, y_test))

KeyboardInterrupt: 

In [ ]:
from tslearn.svm import TimeSeriesSVC
clf = TimeSeriesSVC(C=1.0, kernel="gak")
clf.fit(X_train, y_train)
print(clf.score(X_test, y_test))